version: '3'
services:

  ## INFLUXDB
  influxdb:
    image: influxdb:latest
    volumes:
      - ./influxdb/:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"

  ## INFLUXDB CLI
  influxdb_cli:
    links:
      - influxdb
    image: influxdb:latest
    volumes:
      # Mount for influxdb data directory and configuration
      - ./influxdb:/var/lib/influxdb2:rw
      - ./ssl/influxdb-selfsigned.crt:/etc/ssl/influxdb-selfsigned.crt:rw
      - ./ssl/influxdb-selfsigned.key:/etc/ssl/influxdb-selfsigned.key:rw
      env_file:
        - ./.env
    environment:
      - INFLUXD_TLS_CERT=/etc/ssl/influxdb-selfsigned.crt
      - INFLUXD_TLS_KEY=/etc/ssl/influxdb-selfsigned.key
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    depends_on:
      - influxdb

  ## TELEGRAF
  telegraf:
    image: telegraf:latest
    links:
      - influxdb
    volumes:
      - ./telegraf:/etc/telegraf
    env_file:
      - ./.env
    depends_on:
      - influxdb_cli

volumes:
  influxdbv2:
